/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benyahia
 */
public class affecter extends javax.swing.JFrame {

   
    /**
     * Creates new form affecter
     */
    public affecter() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Sem = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        HoraireAprés = new javax.swing.JComboBox<>();
        HoraireAvant = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EnsBox = new javax.swing.JComboBox<>();
        SalBox = new javax.swing.JComboBox<>();
        MatBox = new javax.swing.JComboBox<>();
        FilBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AvJradioBtnExam = new javax.swing.JRadioButton();
        RatJradioBtnExam = new javax.swing.JRadioButton();
        AvJradioBtn = new javax.swing.JRadioButton();
        RatJradioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DateAvant = new com.toedter.calendar.JDateChooser();
        DateAprés = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        Sem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sem.setForeground(new java.awt.Color(51, 51, 51));
        Sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06" }));
        jPanel1.add(Sem);
        Sem.setBounds(480, 130, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 255));
        jLabel12.setText("Semestre        :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(220, 110, 180, 60);

        HoraireAprés.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HoraireAprés.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08-10", "10-12", "13-15", "15-17" }));
        HoraireAprés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraireAprésActionPerformed(evt);
            }
        });
        jPanel1.add(HoraireAprés);
        HoraireAprés.setBounds(790, 390, 70, 30);

        HoraireAvant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HoraireAvant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08-10", "10-12", "13-15", "15-17" }));
        HoraireAvant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraireAvantActionPerformed(evt);
            }
        });
        jPanel1.add(HoraireAvant);
        HoraireAvant.setBounds(790, 340, 70, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Affecter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 490, 290, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 255));
        jLabel11.setText("à :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(690, 390, 30, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 255));
        jLabel10.setText("Aura lieu le    :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 380, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 255));
        jLabel9.setText("à :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(690, 340, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 255));
        jLabel8.setText("La séance du :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 330, 190, 50);

        EnsBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(EnsBox);
        EnsBox.setBounds(700, 210, 180, 30);

        SalBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(SalBox);
        SalBox.setBounds(700, 260, 180, 30);

        MatBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(MatBox);
        MatBox.setBounds(240, 260, 180, 30);

        FilBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FilBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilBoxActionPerformed(evt);
            }
        });
        jPanel1.add(FilBox);
        FilBox.setBounds(240, 210, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 255));
        jLabel7.setText("Salle       :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 250, 130, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("Filiére        :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 200, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Matiére      :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 250, 141, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Enseignant  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 190, 180, 60);

        AvJradioBtnExam.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(AvJradioBtnExam);
        AvJradioBtnExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AvJradioBtnExam.setForeground(new java.awt.Color(255, 255, 255));
        AvJradioBtnExam.setText("Avancement");
        AvJradioBtnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvJradioBtnExamActionPerformed(evt);
            }
        });
        jPanel1.add(AvJradioBtnExam);
        AvJradioBtnExam.setBounds(710, 60, 120, 30);

        RatJradioBtnExam.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RatJradioBtnExam);
        RatJradioBtnExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RatJradioBtnExam.setForeground(new java.awt.Color(255, 255, 255));
        RatJradioBtnExam.setText("Rattrapage");
        RatJradioBtnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatJradioBtnExamActionPerformed(evt);
            }
        });
        jPanel1.add(RatJradioBtnExam);
        RatJradioBtnExam.setBounds(440, 60, 100, 30);

        AvJradioBtn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(AvJradioBtn);
        AvJradioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AvJradioBtn.setForeground(new java.awt.Color(255, 255, 255));
        AvJradioBtn.setSelected(true);
        AvJradioBtn.setText("Avancement");
        AvJradioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvJradioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AvJradioBtn);
        AvJradioBtn.setBounds(620, 20, 120, 30);

        RatJradioBtn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RatJradioBtn);
        RatJradioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RatJradioBtn.setForeground(new java.awt.Color(255, 255, 255));
        RatJradioBtn.setText("Rattrapage");
        RatJradioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatJradioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RatJradioBtn);
        RatJradioBtn.setBounds(350, 20, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Contrôle/Examen :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 50, 190, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Séance réguliére  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 10, 180, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 570, 150, 40);

        DateAvant.setDateFormatString("d MMM  yyyy");
        jPanel1.add(DateAvant);
        DateAvant.setBounds(360, 340, 170, 30);
        jPanel1.add(DateAprés);
        DateAprés.setBounds(360, 390, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\uséf\\Desktop\\pfe.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        affect e = new affect();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RatJradioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatJradioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatJradioBtnActionPerformed

    private void AvJradioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvJradioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvJradioBtnActionPerformed

    private void RatJradioBtnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatJradioBtnExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatJradioBtnExamActionPerformed

    private void AvJradioBtnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvJradioBtnExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvJradioBtnExamActionPerformed

    private void FilBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
try{
    //test de dimanche
    Date s = DateAprés.getDate();
    String jour = "E";
    SimpleDateFormat edf = new SimpleDateFormat(jour);
    System.out.println(edf.format(s));
    
    Date y = DateAvant.getDate();
    String jour1 = "E";
    SimpleDateFormat ndf = new SimpleDateFormat(jour1);
    System.out.println(ndf.format(y));
    
    //test horaire 
     boolean aaa = true;
     boolean bbb = true;
     if(RatJradioBtn.isSelected() || RatJradioBtnExam.isSelected()){
         int comparaison1 = DateAprés.getDate().compareTo(DateAvant.getDate());
         if(comparaison1>0){
             aaa = false;
         }
     }
     
     
     if(AvJradioBtn.isSelected() || AvJradioBtnExam.isSelected()){
         int comparaison2 = DateAvant.getDate().compareTo(DateAprés.getDate());
         if(comparaison2>0){
             bbb = false;
         }
     }
    
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
     String d = sdf.format(DateAprés.getDate());
     SimpleDateFormat zdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
     String pp = zdf.format(DateAvant.getDate());
    String xx , ww , vv ,qq ,ss, rr ;
    int ee , nn;
    boolean cc = false;
    boolean tt = false;
    boolean mm = false;
    String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cnx = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            ste = cnx.createStatement();
            
            //Test de capacité de la salle (fausse)
            
            
            
            
            
            
            //Test de disponibilité du salle
            rse = ste.executeQuery("select Salle, DateAprés, HoraireAprés from Affectation");
            while(rse.next()){
                qq = rse.getString("Salle");
                ss = rse.getString("DateAprés");
                rr = rse.getString("HoraireAprés");
                if((d.equalsIgnoreCase(ss)) && (HoraireAprés.getSelectedItem().toString().equalsIgnoreCase(rr)) && (SalBox.getSelectedItem().toString().equalsIgnoreCase(qq)) ){
                    tt = true;
                    break;
                }
            }
            
            
            //Test de disponibilité du prof
            rse = ste.executeQuery("select Enseignant, DateAprés, HoraireAprés from Affectation");
            while(rse.next()){
                vv = rse.getString("Enseignant");
                xx = rse.getString("DateAprés");
                ww = rse.getString("HoraireAprés");
                if((d.equalsIgnoreCase(xx)) && (HoraireAprés.getSelectedItem().toString().equalsIgnoreCase(ww)) && (EnsBox.getSelectedItem().toString().equalsIgnoreCase(vv)) ){
                    cc = true;
                    break;
                }
            }
            
       if(cc == false){    
           if(tt == false){
               if(aaa == false ||bbb == false){
                   if(!edf.format(s).equalsIgnoreCase("dim.") && !ndf.format(y).equalsIgnoreCase("dim.")){
    if(JOptionPane.showConfirmDialog(null, "confirmer l'affectation  ?","Affecter",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
        if(RatJradioBtn.isSelected()){ //radiobouton rattrapage séance réguliére
              ste.executeUpdate("insert into Affectation (TypeSéance,TypeAffec,Semestre,Enseignant,Matiére,Filiére,Salle,DateAvant,HoraireAvant,DateAprés,HoraireAprés) values ('Réguliére','Rattrapage','"+Sem.getSelectedItem().toString()+"','"+EnsBox.getSelectedItem().toString()+"','"+MatBox.getSelectedItem().toString()+"','"+FilBox.getSelectedItem().toString()+"','"+SalBox.getSelectedItem().toString()+"','"+pp+"','"+HoraireAvant.getSelectedItem().toString()+"','"+d+"','"+HoraireAprés.getSelectedItem().toString()+"')");
              JOptionPane.showMessageDialog(null, "Affectation effectuée ");
          }else if(AvJradioBtn.isSelected()){ //radiobouton rattrapage séance réguliére
              ste.executeUpdate("insert into Affectation (TypeSéance,TypeAffec,Semestre,Enseignant,Matiére,Filiére,Salle,DateAvant,HoraireAvant,DateAprés,HoraireAprés) values ('Réguliére','Avancement','"+Sem.getSelectedItem().toString()+"','"+EnsBox.getSelectedItem().toString()+"','"+MatBox.getSelectedItem().toString()+"','"+FilBox.getSelectedItem().toString()+"','"+SalBox.getSelectedItem().toString()+"','"+pp+"','"+HoraireAvant.getSelectedItem().toString()+"','"+d+"','"+HoraireAprés.getSelectedItem().toString()+"')");
              JOptionPane.showMessageDialog(null, "Affectation effectuée ");
          }else if(RatJradioBtnExam.isSelected()){ //radiobouton rattrapage séance réguliére
              ste.executeUpdate("insert into Affectation (TypeSéance,TypeAffec,Semestre,Enseignant,Matiére,Filiére,Salle,DateAvant,HoraireAvant,DateAprés,HoraireAprés) values ('Contrôle/Exam','Rattrapage','"+Sem.getSelectedItem().toString()+"','"+EnsBox.getSelectedItem().toString()+"','"+MatBox.getSelectedItem().toString()+"','"+FilBox.getSelectedItem().toString()+"','"+SalBox.getSelectedItem().toString()+"','"+pp+"','"+HoraireAvant.getSelectedItem().toString()+"','"+d+"','"+HoraireAprés.getSelectedItem().toString()+"')");
              JOptionPane.showMessageDialog(null, "Affectation effectuée ");
          }else if(AvJradioBtnExam.isSelected()){ //radiobouton rattrapage séance réguliére
              ste.executeUpdate("insert into Affectation (TypeSéance,TypeAffec,Semestre,Enseignant,Matiére,Filiére,Salle,DateAvant,HoraireAvant,DateAprés,HoraireAprés) values ('Contrôle/Exam','Avancement','"+Sem.getSelectedItem().toString()+"','"+EnsBox.getSelectedItem().toString()+"','"+MatBox.getSelectedItem().toString()+"','"+FilBox.getSelectedItem().toString()+"','"+SalBox.getSelectedItem().toString()+"','"+pp+"','"+HoraireAvant.getSelectedItem().toString()+"','"+d+"','"+HoraireAprés.getSelectedItem().toString()+"')");
              JOptionPane.showMessageDialog(null, "Affectation effectuée ");
          }
    }
                   }else{
              JOptionPane.showMessageDialog(null, "              Affectaion Impossible !\n'Le Dimanche est indisponible pour enseigner'  "); 
           }
               }else{
              JOptionPane.showMessageDialog(null, "Opération non autorisé\nVérifiez le type d'affectation ! "); 
           }
           }else{
              JOptionPane.showMessageDialog(null, "Salle indisponible pour cet horaire ! "); 
           }
       }else {
           JOptionPane.showMessageDialog(null, "Enseignant indisponible pour cet horaire ! ");
       }
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, "Erreur d'affectation !!\n"+e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
       try{
            String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cnx = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            ste = cnx.createStatement();
            rse = ste.executeQuery("select NomEns, PrenomEns from Enseignant");
            EnsBox.removeAllItems();
            String a,b;
            while(rse.next()){
                a = rse.getString(1);
                b = rse.getString(2);
                EnsBox.addItem(a+" "+b);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur\n"+e.getMessage());
        }
        
        try{
            String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cnx = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            ste = cnx.createStatement();
            rse = ste.executeQuery("select NomMat from Matiére");
            MatBox.removeAllItems();
            String c;
            while(rse.next()){
                c = rse.getString(1);
                MatBox.addItem(c);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur\n"+e.getMessage());
        }
        
        try{
            String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cnx = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            ste = cnx.createStatement();
            rse = ste.executeQuery("select NomFil from Filiére");
            FilBox.removeAllItems();
            String d;
            while(rse.next()){
                d = rse.getString(1);
                FilBox.addItem(d);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur\n"+e.getMessage());
        }
        
        try{
            String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cnx = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            ste = cnx.createStatement();
            rse = ste.executeQuery("select Libel from Salle");
            SalBox.removeAllItems();
            String e;
            while(rse.next()){
                e = rse.getString(1);
                SalBox.addItem(e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur\n"+e.getMessage());
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void HoraireAprésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraireAprésActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraireAprésActionPerformed

    private void EnsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnsBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EnsBoxActionPerformed

    private void HoraireAvantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraireAvantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraireAvantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affecter().setVisible(true);
            }
        });
    }

    private Statement ste;
    private ResultSet rse;
    private Connection cnx;
    private DefaultTableModel tb;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AvJradioBtn;
    private javax.swing.JRadioButton AvJradioBtnExam;
    private com.toedter.calendar.JDateChooser DateAprés;
    private com.toedter.calendar.JDateChooser DateAvant;
    private javax.swing.JComboBox<String> EnsBox;
    private javax.swing.JComboBox<String> FilBox;
    private javax.swing.JComboBox<String> HoraireAprés;
    private javax.swing.JComboBox<String> HoraireAvant;
    private javax.swing.JComboBox<String> MatBox;
    private javax.swing.JRadioButton RatJradioBtn;
    private javax.swing.JRadioButton RatJradioBtnExam;
    private javax.swing.JComboBox<String> SalBox;
    private javax.swing.JComboBox<String> Sem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void close() {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}

