/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Benyahia
 */
public class affect extends javax.swing.JFrame {

    /**
     * Creates new form affect
     */
    public affect() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeconexionBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        affecterbtn = new javax.swing.JButton();
        consulterbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("d'imprimer chaque affectation afin de l'afficher ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 570, 420, 20);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consulter la liste des affectations et permettre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 530, 410, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  et d'avancement selon la demande");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(610, 570, 340, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Affecter des séances de rattrapage ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(610, 530, 350, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\uséf\\Desktop\\photop.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 130, 760, 310);

        DeconexionBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DeconexionBtn.setText("Deconexion");
        DeconexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconexionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeconexionBtn);
        DeconexionBtn.setBounds(800, 10, 160, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("   MENU PRINCIPAL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 30, 620, 90);

        affecterbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        affecterbtn.setForeground(new java.awt.Color(51, 51, 51));
        affecterbtn.setText("Affecter");
        affecterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affecterbtnActionPerformed(evt);
            }
        });
        jPanel1.add(affecterbtn);
        affecterbtn.setBounds(650, 460, 210, 60);

        consulterbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        consulterbtn.setForeground(new java.awt.Color(51, 51, 51));
        consulterbtn.setText("Imprimer");
        consulterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterbtnActionPerformed(evt);
            }
        });
        jPanel1.add(consulterbtn);
        consulterbtn.setBounds(100, 460, 210, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\uséf\\Desktop\\pfe.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affecterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affecterbtnActionPerformed
        // TODO add your handling code here:
        close();
        affecter b = new affecter();
        b.setVisible(true);
        
    }//GEN-LAST:event_affecterbtnActionPerformed

    private void consulterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterbtnActionPerformed
        // TODO add your handling code here:
        close();
        consulter c = new consulter();
        c.setVisible(true);
    }//GEN-LAST:event_consulterbtnActionPerformed

    private void DeconexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconexionBtnActionPerformed
        // TODO add your handling code here:
        close();
        login zz = new login();
        zz.setVisible(true);
    }//GEN-LAST:event_DeconexionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeconexionBtn;
    private javax.swing.JButton affecterbtn;
    private javax.swing.JButton consulterbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
