/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author Benyahia
 */
public class consulter extends javax.swing.JFrame {

    /**
     * Creates new form consulter
     */
    public consulter() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        chercherbtn = new javax.swing.JButton();
        consultertxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(800, 560, 150, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 360, 700, 160);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 130, 990, 200);

        chercherbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chercherbtn.setText("Chercher");
        chercherbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherbtnActionPerformed(evt);
            }
        });
        jPanel1.add(chercherbtn);
        chercherbtn.setBounds(810, 60, 140, 40);

        consultertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultertxtActionPerformed(evt);
            }
        });
        jPanel1.add(consultertxt);
        consultertxt.setBounds(810, 20, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Enseignant        :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 0, 200, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 560, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\uséf\\Desktop\\pfe.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        affect e = new affect();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultertxtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            String url = "jdbc:odbc:manuu";
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //cn = DriverManager.getConnection("jdbc:odbc:database");
            cn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\uséf\\Desktop\\database22.accdb");
            st = cn.createStatement();
            
            tb = new DefaultTableModel();
            tb.addColumn("Type séance");
            tb.addColumn("Type affectation");
            tb.addColumn("Semestre");
            tb.addColumn("Enseignant");
            tb.addColumn("Matiére");
            tb.addColumn("Filiére");
            tb.addColumn("Salle");
            tb.addColumn("Date Avant");
            tb.addColumn("Horaire Avant");
            tb.addColumn("Date Aprés");
            tb.addColumn("Horaire Aprés");
            Table1.setModel(tb);
            afficherliste();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de connexion\n"+e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void chercherbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherbtnActionPerformed
        // TODO add your handling code here:
        try{
            tb.setRowCount(0); // vider la liste des chauffeurs
            
            
              rs = st.executeQuery("select TypeSéance, TypeAffec, Semestre, Enseignant, Matiére, Filiére, Salle, DateAvant, HoraireAvant, DateAprés, HoraireAprés from Affectation where Enseignant like '%"+consultertxt.getText()+"%'");
           
            
            while(rs.next()){
            t1 = rs.getString("TypeSéance");
            t2 = rs.getString("typeAffec");
            Semestre = rs.getString("Semestre");
            Ens = rs.getString("Enseignant");
            Mat = rs.getString("Matiére");
            Fil = rs.getString("Filiére");
            Sal = rs.getString("Salle");
            d1 = rs.getString("DateAvant");
            Ho1 = rs.getString("HoraireAvant");
            d2 = rs.getString("DateAprés");
            Ho2 = rs.getString("HoraireAprés");
            Object[] o = {t1,t2,Semestre,Ens,Mat,Fil,Sal,d1,Ho1,d2,Ho2};
            tb.addRow(o);
            }
                if(tb.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Auccune affectation pour cet enseignant !");
                    afficherliste(); 
                
                }
        
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur bouton rechercher la liste\n"+e.getMessage());
        }
    }//GEN-LAST:event_chercherbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(!jTextArea1.getText().equalsIgnoreCase("")){
        try{
            
            boolean complete = jTextArea1.print();
            if(complete){
                JOptionPane.showMessageDialog(null,"Impression réussi !","Information",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Imprerssion interrompu !","Information",JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
      }else{
          JOptionPane.showMessageDialog(null, "Erreur \nImpossible d'imprimer page vide !");
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        
        String nn = "Type de séance :  "+ Table1.getValueAt(Table1.getSelectedRow(), 0).toString()+"\t\t"+Table1.getValueAt(Table1.getSelectedRow(), 1).toString()+"\nSemestre :  "+ Table1.getValueAt(Table1.getSelectedRow(), 2).toString()+"\t\tFiliére :  "+Table1.getValueAt(Table1.getSelectedRow(), 5).toString()+"\nEnseignant :  "+ Table1.getValueAt(Table1.getSelectedRow(), 3).toString()+"\tMatiére :  "+Table1.getValueAt(Table1.getSelectedRow(), 4).toString()+"\nLa séance de : "+ Table1.getValueAt(Table1.getSelectedRow(), 7).toString()+"\t\tà :  "+Table1.getValueAt(Table1.getSelectedRow(), 8).toString()+"\nAura lieu le : "+ Table1.getValueAt(Table1.getSelectedRow(), 9).toString()+"\t\tà :  "+Table1.getValueAt(Table1.getSelectedRow(), 10).toString()+"\n\tDans la salle : "+ Table1.getValueAt(Table1.getSelectedRow(), 6).toString();
        jTextArea1.setText(nn);
    }//GEN-LAST:event_Table1MouseClicked

    //Procedure afficher la liste des affectation
    private void afficherliste(){
        try{
            tb.setRowCount(0); //vider la liste
            rs = st.executeQuery("select TypeSéance, TypeAffec, Semestre, Enseignant, Matiére, Filiére, Salle,DateAvant, HoraireAvant, DateAprés, HoraireAprés from Affectation");
        
        while(rs.next()){
            t1 = rs.getString("TypeSéance");
            t2 = rs.getString("typeAffec");
            Semestre = rs.getString("Semestre");
            Ens = rs.getString("Enseignant");
            Mat = rs.getString("Matiére");
            Fil = rs.getString("Filiére");
            Sal = rs.getString("Salle");
            d1 = rs.getString("DateAvant");
            Ho1 = rs.getString("HoraireAvant");
            d2 = rs.getString("DateAprés");
            Ho2 = rs.getString("HoraireAprés");
            Object[] o = {t1,t2,Semestre,Ens,Mat,Fil,Sal,d1,Ho1,d2,Ho2};
            tb.addRow(o);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur afficher la liste\n"+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulter().setVisible(true);
            }
        });
    }
    //Declaration des variables
    private Connection cn;
    private ResultSet rs;
    private Statement st;
    private DefaultTableModel tb;
    private int i;
    private String t1, t2, Ens, Mat, Fil, Sal, Ho1, d1, Ho2, d2, Semestre;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton chercherbtn;
    private javax.swing.JTextField consultertxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
private void close() {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
